=== l3miage-couliban/TuxLetterGame/build/classes/data/xsd/profil.xsd
<?xml version="1.0"?>
<!--
Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
Click nbfs://nbhost/SystemFileSystem/Templates/XML/XmlSchema.xsd to edit this template
-->

<schema version="1.0"
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://myGame/tux"
        xmlns:pr="http://myGame/tux" 
        
        elementFormDefault="qualified">
    
    
    <element name="profil" type="pr:Profil"/>
    
    
    <complexType name="Profil">
        <sequence>
            <element name="nom" type="string"/>
            <element name="avatar" type="string"/>
            <element name="anniversaire" type="date"/>
            <element name="parties" type="pr:Parties"/>
        </sequence>
    </complexType>
    
    <complexType name="Parties">
        <sequence>
            <element name="partie" type="pr:Partie" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <complexType name="Partie">
        <sequence>
            <element name="temps" type="double"/>
            <element name="mot" type="pr:Mot"/>
        </sequence>
        <attribute name="id" type="int"/>
        <attribute name="date" type="date"/>
        <attribute name="trouvé" type="string"/>
    </complexType>
    
    
    
    <complexType name="Mot">
        <simpleContent>
            <extension base ="pr:Motsimple">
                <attribute name="niveau" type="int"/>
            </extension>
        </simpleContent>
    </complexType>
    
    <simpleType name="Motsimple">
        <restriction base="string">
            <pattern value="[a-zA-Zà-ü\-]{2,}" />
        </restriction>
    </simpleType>
    

</schema>

=== l3miage-couliban/TuxLetterGame/build/classes/data/xml/profil.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
    Document   : save_example.xml.xml
    Created on : August 31, 2014, 3:31 PM
    Author     : Johan Sarrazin / Céline Fouard / Nicolas Glade
    Description:
        Purpose of the document follows.
-->
<profil xmlns="http://myGame/tux" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://myGame/tux ../xsd/profil.xsd">
    <nom>Alban</nom>
    <avatar>../images/bear.png</avatar>
    <anniversaire>2006-05-08</anniversaire>
    <parties>
        <partie id="1" date="2013-12-10">
            <temps>20.0</temps>
            <mot niveau="1">cle</mot>
        </partie>
        <partie id="2" date="2013-12-11" trouvé="75%">
            <temps>15.0</temps>
            <mot niveau="2">indice</mot>
        </partie>
        <partie id="3" date="2013-12-11">
            <temps>12.0</temps>
            <mot niveau="2">indice</mot>
        </partie>
    </parties>
</profil>
